name: App Python to test GitHub Actions

on: [push, pull_request]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.12.6
            uses: actions/setup-python@v5
            with:
                python-version: 3.12.6
        - name: Install dependencies
            run: |
            python -m pip install --upgrade pip
            pip install pytest
        - name: Teste com Pytest
            run: |
            pytest